name: Remove unused stubtest allowlist entries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  stubtest:
    if: github.repository == 'python/typeshed'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10.0-beta.1']
      fail-fast: false

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install $(grep mypy== requirements-tests-py3.txt)
      - name: Run stubtest
        shell: bash
        run: ./tests/stubtest_unused.py | tee stubtest-output-${{ matrix.os }}-${{ matrix.python-version }}
      - name: Store output
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: stubtest-output
          path: stubtest-output-${{ matrix.os }}-${{ matrix.python-version }}

  collate:
    if: github.repository == 'python/typeshed'
    runs-on: ubuntu-latest
    needs: stubtest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
      - name: Get stubtest outputs
        uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2.1.1
        with:
          name: stubtest-output
      - name: Collate duplicates
        run: cat stubtest-output-* | sort -u | tee stubtest-output
      - name: Remove entries from allowlists
        run: python scripts/update-stubtest-allowlist.py stubtest-output
      - name: Create pull request
        # v3.8.2
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Remove unused stubtest allowlist entries
          title: "[gh-action] Remove unused stubtest allowlist entries"
          base: master
